name: Build and Deploy

on:
  push:
    branches:
      - main # atau branch sumber Anda

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    # TAMBAHKAN BLOK INI
    permissions:
      contents: write
      
    steps:
   # ... (setelah langkah Checkout) ...

      - name: Build static files
        run: |
          mkdir output
          cp index.html output/
          cp -R css output/
          cp -R js output/
          # Salin semua file dan folder lain yang dibutuhkan ke dalam 'output'

      - name: Deploy 🚀
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          build_dir: output # Sekarang folder ini sudah ada
