name: Build and Deploy

on:
  push:
    branches:
      - main # atau branch sumber Anda

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    # TAMBAHKAN BLOK INI
    permissions:
      contents: write
      
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      # ... langkah-langkah build Anda ...

      - name: Deploy 🚀
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          # Hapus tanda # dari baris di bawah ini untuk mengaktifkannya
          build_dir: output
